[package]
name = "rivet-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Command-line tool for Rivet, mainly for testing rivet-core."
publish = false

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive", "env"] }
png = "0.18.1"
rivet-core = { version = "0.0.1", path = "../rivet-core" }

[lints]
workspace = true
