// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What people who open a protected file (without the owner password) may do.
 */
export type Allowed = { print: boolean, copy: boolean, 
/**
 * Change the pages and their content.
 */
edit: boolean, fillForms: boolean, 
/**
 * Add comments and other annotations (and fill forms).
 */
annotate: boolean, };
