// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationKind } from "./AnnotationKind";
import type { Color } from "./Color";
import type { PageRect } from "./PageRect";

/**
 * One annotation on a page.
 */
export type Annotation = { 
/**
 * Identifies the annotation on its page (its `/NM` name). Empty when adding one.
 */
id: string, kind: AnnotationKind, 
/**
 * Where it is on the page. For squares, circles, notes and stamps this is
 * their shape; for the others it's worked out from the shape.
 */
rect: PageRect, color: Color, 
/**
 * 0 (invisible) to 1 (opaque).
 */
opacity: number, 
/**
 * Line width in points.
 */
width: number, 
/**
 * The comment text.
 */
contents: string, author: string, 
/**
 * When it was last changed (ISO 8601), if known.
 */
modified: string | null, 
/**
 * PDFRivet can change it (otherwise it can only be deleted).
 */
editable: boolean, };
