// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { MarkupStyle } from "./MarkupStyle";
import type { PagePoint } from "./PagePoint";
import type { PageRect } from "./PageRect";

/**
 * What kind of annotation it is, with its shape.
 */
export type AnnotationKind = { "kind": "markup", style: MarkupStyle, quads: Array<PageRect>, } | { "kind": "ink", strokes: Array<Array<PagePoint>>, } | { "kind": "square", fill: Color | null, } | { "kind": "circle", fill: Color | null, } | { "kind": "line", from: PagePoint, to: PagePoint, arrow: boolean, } | { "kind": "note" } | { "kind": "stamp" } | { "kind": "other", subtype: string, };
