// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageAnnotations } from "./PageAnnotations";

/**
 * Annotations of several pages, read a batch at a time (see [`crate::Document::annotations_from`]).
 */
export type AnnotationBatch = { pages: Array<PageAnnotations>, 
/**
 * Where to continue, or `None` after the last page.
 */
nextPage: number | null, };
