// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How hard to compress.
 */
export type CompressLevel = "lossless" | "balanced" | "strong";
