// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageSize } from "./PageSize";

/**
 * Basic facts about an open document, sent to the UI after opening.
 */
export type DocInfo = { pageCount: number, title: string | null, author: string | null, 
/**
 * Size of every page, so the viewer can lay out pages before rendering them.
 */
pageSizes: Array<PageSize>, 
/**
 * The text reads right to left (e.g. Arabic), so two-page spreads start on the right.
 */
rtl: boolean, 
/**
 * The document allows copying its text.
 */
canCopy: boolean, 
/**
 * The document allows adding and changing annotations.
 */
canAnnotate: boolean, 
/**
 * Bookmarks can be added and changed (not in password-protected files yet).
 */
canEditOutline: boolean, 
/**
 * Comments can be answered (replies need the same rewrite as bookmarks).
 */
canReply: boolean, 
/**
 * Pages can be moved, rotated, deleted, inserted and taken out into other
 * files (the author's permissions allow assembling the document).
 */
canAssemble: boolean, 
/**
 * The document's author allows printing it.
 */
canPrint: boolean, };
