// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageSize } from "./PageSize";

/**
 * Basic facts about an open document, sent to the UI after opening.
 */
export type DocInfo = { pageCount: number, title: string | null, author: string | null, 
/**
 * Size of every page, so the viewer can lay out pages before rendering them.
 */
pageSizes: Array<PageSize>, 
/**
 * The text reads right to left (e.g. Arabic), so two-page spreads start on the right.
 */
rtl: boolean, 
/**
 * The document allows copying its text.
 */
canCopy: boolean, 
/**
 * The document allows adding and changing annotations.
 */
canAnnotate: boolean, };
