// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from "./Metadata";
import type { Permissions } from "./Permissions";

/**
 * Everything shown in the Document properties dialog.
 */
export type DocProperties = { metadata: Metadata, creator: string, producer: string, 
/**
 * ISO 8601 dates (e.g. `2026-09-13T20:21:56+03:00`), when the PDF has them.
 */
created: string | null, modified: string | null, pdfVersion: string, pageCount: number, fileName: string, folder: string, fileSize: number, tagged: boolean, encrypted: boolean, permissions: Permissions, 
/**
 * Title, author… can be changed (not for password-protected files yet).
 */
canEditMetadata: boolean, };
