// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A change the user made to a field.
 */
export type FieldChange = { "kind": "toggle" } | { "kind": "text", value: string, } | { "kind": "select", option: number, };
