// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of field this is, with its current value.
 */
export type FieldKind = { "kind": "text", value: string, multiline: boolean, password: boolean, } | { "kind": "checkbox", checked: boolean, } | { "kind": "radio", checked: boolean, } | { "kind": "choice", options: Array<string>, selected: number | null, } | { "kind": "other" };
