// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A font family that can be chosen, for the font picker.
 */
export type FontInfo = { family: string, bundled: boolean, 
/**
 * It has Arabic letters.
 */
arabic: boolean, };
