// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldKind } from "./FieldKind";

/**
 * One form field widget on a page.
 */
export type FormField = { 
/**
 * Position of the widget among the page's annotations; identifies it in changes.
 */
index: number, name: string | null, readOnly: boolean, 
/**
 * Where the field is, as fractions of the page (top-left origin, before view rotation).
 */
left: number, top: number, right: number, bottom: number, field: FieldKind, };
