// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PagePaper } from "./PagePaper";

/**
 * How pictures are placed on pages.
 */
export type ImageLayout = { paper: PagePaper, 
/**
 * Space around the picture, in points.
 */
margin: number, };
