// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a link goes.
 */
export type LinkTarget = { "kind": "page", page: number, } | { "kind": "uri", uri: string, };
