// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One merged file: where its pages went in the merged document.
 */
export type MergePart = { 
/**
 * The open document the pages came from.
 */
doc: number, 
/**
 * Its pages that were copied (0-based), in order.
 */
pages: Array<number>, 
/**
 * The merged document's page where they start.
 */
start: number, 
/**
 * Names its bookmark (usually the file name).
 */
title: string, };
