// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The editable part of the document's description.
 */
export type Metadata = { title: string, author: string, subject: string, keywords: string, };
