// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the outline. `page` is `None` when the entry doesn't point
 * to a page in this document (for example, a web link).
 */
export type OutlineItem = { title: string, page: number | null, children: Array<OutlineItem>, };
