// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Page size in PDF points (1 pt = 1/72 inch).
 */
export type PageSize = { width: number, height: number, };
