// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point as fractions (0..1) of the page, top-left origin, before view rotation.
 */
export type PagePoint = { x: number, y: number, };
