// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a page of the new arrangement comes from.
 */
export type PageSource = { "kind": "page", index: number, } | { "kind": "other", doc: number, index: number, } | { "kind": "blank", width: number, height: number, };
