// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkTarget } from "./LinkTarget";

/**
 * A link area on the page. The rectangle is given as fractions (0..1) of the
 * page, measured from its top-left corner, before any view rotation, so the
 * UI can place it at any zoom.
 */
export type PageLink = { left: number, top: number, right: number, bottom: number, target: LinkTarget, };
