// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pages of a document made from pictures are this size.
 */
export type PagePaper = "image" | "a4" | "letter";
