// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rectangle as fractions (0..1) of the page, top-left origin, before view rotation.
 */
export type PageRect = { left: number, top: number, right: number, bottom: number, };
