// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageSource } from "./PageSource";

/**
 * One page of a new arrangement, in order.
 */
export type PageSlot = { source: PageSource, 
/**
 * Quarter turns clockwise added to the page's own rotation (negative: counter-clockwise).
 */
turns: number, };
