// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A paper size a printer offers.
 */
export type Paper = { 
/**
 * The printer's own identifier (a Windows paper number or a CUPS keyword).
 */
id: string, name: string, widthMm: number, heightMm: number, };
