// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the document allows (as set by its author when protecting it).
 */
export type Permissions = { print: boolean, copy: boolean, modify: boolean, fillForms: boolean, annotate: boolean, };
