// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one page goes on its sheet of paper. All values are in points
 * (1/72 inch), measured from the sheet's top-left corner.
 */
export type Placement = { landscape: boolean, sheetWidth: number, sheetHeight: number, x: number, y: number, width: number, height: number, scale: number, };
