// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Paper } from "./Paper";

/**
 * A printer and what it can do.
 */
export type PrinterInfo = { name: string, isDefault: boolean, papers: Array<Paper>, 
/**
 * Id of the paper the printer uses by default.
 */
defaultPaper: string | null, duplex: boolean, color: boolean, 
/**
 * The printer's own settings window is available ("Printer properties…").
 */
hasProperties: boolean, };
