// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duplex } from "./Duplex";
import type { Orientation } from "./Orientation";
import type { Scaling } from "./Scaling";

/**
 * Everything chosen in the print dialog.
 */
export type PrintSettings = { printer: string, 
/**
 * 0-based pages, in the order they should print.
 */
pages: Array<number>, copies: number, collate: boolean, scaling: Scaling, orientation: Orientation, duplex: Duplex, grayscale: boolean, 
/**
 * Paper id from [`PrinterInfo::papers`]; `None` uses the printer's default.
 */
paper: string | null, 
/**
 * Document title shown in the printer queue.
 */
title: string, };
