// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Allowed } from "./Allowed";

/**
 * What the next save does about passwords.
 */
export type Protection = { "kind": "set", openPassword: string, ownerPassword: string, allowed: Allowed, } | { "kind": "remove" };
