// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Clockwise view rotation. Only affects rendering; the file is never changed.
 */
export type Rotation = "None" | "Cw90" | "Cw180" | "Cw270";
