// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Scaling = { "kind": "fit" } | { "kind": "actual" } | { "kind": "shrink" } | { "kind": "custom", percent: number, };
