// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to look for.
 */
export type SearchQuery = { text: string, 
/**
 * Upper and lower case must match (otherwise "pdf" finds "PDF").
 */
matchCase: boolean, 
/**
 * Only whole words ("cat" doesn't find "category").
 */
wholeWord: boolean, };
