// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchHit } from "./SearchHit";

/**
 * The results of searching some pages.
 */
export type SearchBatch = { hits: Array<SearchHit>, 
/**
 * Where to continue, or `None` when the last page has been searched.
 */
nextPage: number | null, };
