// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One place the text was found.
 */
export type SearchHit = { page: number, 
/**
 * The matching characters: `start..end` (character positions, as in a selection).
 */
start: number, end: number, 
/**
 * Some text around the match, for the list of results.
 */
before: string, text: string, after: string, };
