// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where lines sit across the box.
 */
export type TextAlign = "auto" | "left" | "center" | "right";
