// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextAlign } from "./TextAlign";
import type { TextDirection } from "./TextDirection";
import type { TextFont } from "./TextFont";
import type { VerticalAlign } from "./VerticalAlign";

/**
 * How a text box's text looks and where it goes.
 */
export type TextStyle = { font: TextFont, 
/**
 * Font size in points.
 */
size: number, bold: boolean, align: TextAlign, valign: VerticalAlign, direction: TextDirection, 
/**
 * Lines wrap at this width (points); `None`: the box grows with the text.
 */
width: number | null, 
/**
 * The box's height (points) when it's taller than the text; `None`: it fits the text.
 */
height: number | null, };
