// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A text box's size in points, padding included.
 */
export type TextBoxSize = { width: number, height: number, };
