// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stretch of text across pages: from character `start` on `startPage` up to
 * (not including) character `end` on `endPage`. An `end` past the last
 * character means "to the end of that page".
 */
export type TextRange = { startPage: number, start: number, endPage: number, end: number, };
