// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A font chosen for a text box.
 */
export type TextFont = { family: string, 
/**
 * One of PDFRivet's own fonts (otherwise installed on the computer).
 */
bundled: boolean, };
