// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the text sits in a box taller than it.
 */
export type VerticalAlign = "top" | "middle" | "bottom";
